is_sep_task_exp: true

# dummy
cached_ocl_error_ds: "/home/xsjin/cl-analysis/runs/instance-p3-flan-t5-large/vanilla_bg100_step30_adam_full_greedy_eval_mmlu_text-lr1e-6/mmlu/ocl_error_ds.csv"

stream:
  n_batch_per_stream: 10

random_pt:
  min_seed: 0
  max_seed: 50
  train_ts: 1000
  train_bs: 8
  use_cache: true

templates:
  my_seed: -1

pt_tasks:
  - glue-mrpc
  - glue-qqp

output_dir: "runs/flan-t5-large/debug_step/{my_seed}"
load_ckpt: "/home/xsjin/cl-analysis/runs_rand_pts/flan-t5-large/1k_step/{my_seed}/model_seed_{my_seed}.pt"

seed: "{my_seed}"
