tempates:
  revision: null

pt_revision: "{revision}"
pt_revision_list: "/home/xsjin/cl-analysis/data/olmo_revisions.txt"

output_dir: "runs_olmo_ocl/flan-5k-revisions/revision_{revision}/task_{TASK_ID}"
ref_ocl_step_dir: "/home/xsjin/cl-analysis/runs_olmo_ocl/flan-5k"
use_ref_ocl_train_step: true
ocl_val_step: 100000000