fpd:
  train_aff_log_path: 'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/aff_log.pkl'
  train_ocl_log_path: 'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/fpd_train/ocl_log.pkl'
  dev_aff_log_path:   'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/aff_log.pkl'
  dev_ocl_log_path:   'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/fpd_dev/ocl_log.pkl'

  train_pt_logits_file: 'runs/instance-p3-bart0-large/vanilla_bg100_lr1e-6_step30_sgd_greedy_eval_fixbos-lr1e-2/{task}/concat_pt_logits_eval.pkl'
  dev_pt_logits_file: 'runs/instance-p3-bart0-large/vanilla_bg100_lr1e-6_step30_sgd_greedy_eval_fixbos-lr1e-2/{task}/concat_pt_logits_eval.pkl'

  train_ocl_update_logits_file: 'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/fpd_train/ocl_error_ds_change_v2_logit_change_eval.pkl'
  dev_ocl_update_logits_file:   'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/fpd_dev/ocl_error_ds_change_v2_logit_change_eval.pkl'

  train_concat_pt_ds_dir: 'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/'
  train_ocl_error_ds_dir: 'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/fpd_train/'
  dev_concat_pt_ds_dir:   'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/'
  dev_ocl_error_ds_dir:   'runs/instance-p3-bart0-large/vanilla_bg100_step30_adam_partial_greedy_eval_fixbos-{LR}/{PART}/{task}/fpd_dev/'


max_input_length: 512
templates:
  PART: "unk"
  LR: "lr1e-4"
  STEP: "100"