fpd:
  multi_token: true
  logit_loss_type: 'margin'
  use_margin_variant: true
  ignore_zero_token_kl: true
  margin_loss_reweight: true
  margin_multi_ts: true
  late_pred_forget: true

  margin_sq: true