templates:
  postfix: ""
output_dir: "runs/instance-p3-flan-t5-large/distill_er_coreset{postfix}"

cl_method: "er"
replay_n: -1

replay_freq: 1


# distill
cl_use_distill: true
distill_reduction: "sum"
distill_student_temp: 1.0
distill_teacher_temp: 1.0
distill_alpha: 1.0

use_coreset: true
coreset_bin_dir: "/home/xsjin/cl-analysis/runs/instance-p3-flan-t5-large/vanilla_bg100_coreset/coreset_stat.pkl"
