templates:
  postfix: ""
output_dir: "runs/instance-p3-flan-t5-large/mir1k_distill_er_star{postfix}"

cl_method: "mir"
replay_n: -1

replay_freq: 1

# distill
cl_use_distill: true
distill_reduction: "sum"
distill_student_temp: 1.0
distill_teacher_temp: 1.0
distill_alpha: 1.0

cand_k: 64
