templates:
  postfix: ""
  task: ""
output_dir: "runs/instance-p3-bart0-large/mir_pred_subset_star{postfix}"

cl_method: "mir_pred"

replay_n: -1

replay_freq: 1

pred_forget_file: "runs/instance-p3-bart0-large/vanilla_bg100_lr1e-6_step30_greedy_eval_fixbos/{task}/pred_forget_simple-0.2.subset"

# distill
cl_use_distill: true
distill_reduction: "sum"
distill_student_temp: 1.0
distill_teacher_temp: 1.0
distill_alpha: 1.0
