pretrain_ds_dir: "data/p3_pretrain"
ocl_ds_dir: "data/recross_data"
max_input_length: 512
max_output_length: 128
model_name: "yuchenlin/BART0"
templates:
output_dir: "runs/p3-bart0/super_glue-wsc.fixed"
learning_rate: 1.0e-6

templates:
  seed: 0

num_epoch_per_task: 5
max_step_per_task: -1
per_device_train_batch_size: 8

do_replay: true
replay_freq: 1
replay_k: 8
replay_n_step: 1
replay_n: -1
do_candidate: true
cand_k: 100

mir_with_abs_score: false
optim_module_regex: null
seperate_replay_optimizer: false
replay_optimizer_lr: 1.0e-5

ocl_steps: 10

num_beams: 3
max_grad_norm: 1.0

mir_no_resample: false

ocl_tasks:
  - super_glue-wsc.fixed
  - winogrande-winogrande_xl
  - super_glue-cb
  - super_glue-rte
  - anli
  - super_glue-copa
  # - story_cloze-2016
  - hellaswag
  - super_glue-wic
pt_tasks:
  - glue-mrpc
  - glue-qqp
  - paws_x-en
  - kilt_tasks-hotpotqa
  - wiki_qa
  - adversarial_qa-dbert
  - adversarial_qa-dbidaf
  - adversarial_qa-droberta
  - duorc-SelfRC
  - duorc-ParaphraseRC
  - ropes
  - quoref
  - cos_e-v1.11
  - cosmos_qa
  - dream
  - qasc
  - quail
  - quartz
  - sciq
  - social_i_qa
  - wiki_hop-original
  - wiqa
  - amazon_polarity
  - app_reviews
  - imdb
  - rotten_tomatoes
  - yelp_review_full
  - common_gen
  - wiki_bio
  - cnn_dailymail-3.0.0
  - gigaword
  - multi_news
  - samsum
  - xsum
  - ag_news
  - dbpedia_14