templates:
  posneg_file: placeholder
posneg_file: "{posneg_file}"
task_type: nli_posneg
max_seq_length: 256
model_name: "roberta-base"
max_train_example: 100000
max_dev_example: 10000
max_test_example: 10000
evaluation_strategy: "steps"
eval_steps: 500
learning_rate: 5e-6
save_total_limit: 2
save_steps: 500
save_strategy: "steps"
load_best_model_at_end: true
metric_for_best_model: "acc"
greater_is_better: true

