templates:
  seed: 0
output_dir: "runs/snli-bert/seed{seed}"
task_type: "nli"
dataset_name: "snli"
max_seq_length: 128
model_name: "resources/bert-base-cased"
learning_rate: 1.0e-5
num_epochs: 10
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
save_steps: 10000
seed: "{seed}"